export const postConstants = {
  GET_POST_REQUEST: "GET_POST_PAGE_REQUEST",
  GET_POST_SUCCESS: "GET_POST_PAGE_SUCCESS",
  GET_POST_FAILURE: "GET_POST_PAGE_FAILURE",

  GET_POST_DETAILS_BY_ID_REQUEST: "GET_POST_DETAILS_BY_ID_REQUEST",
  GET_POST_DETAILS_BY_ID_SUCCESS: "GET_POST_DETAILS_BY_ID_SUCCESS",
  GET_POST_DETAILS_BY_ID_FAILURE: "GET_POST_DETAILS_BY_ID_FAILURE",

  DELETE_POST_BY_ID_REQUEST: "DELETE_POST_BY_ID_REQUEST",
  DELETE_POST_BY_ID_SUCCESS: "DELETE_POST_BY_ID_SUCCESS",
  DELETE_POST_BY_ID_FAILURE: "DELETE_POST_BY_ID_FAILURE",

  ADD_POST_REQUEST: "ADD_POST_REQUEST",
  ADD_POST_SUCCESS: "ADD_POST_SUCCESS",
  ADD_POST_FAILURE: "ADD_POST_FAILURE",

  UPDATE_POST_REQUEST: "UPDATE_POST_REQUEST",
  UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
  UPDATE_POST_FAILURE: "UPDATE_POST_FAILURE",

  GET_SEARCH_POST_REQUEST: "GET_SEARCH_POST_REQUEST",
  GET_SEARCH_POST_SUCCESS: "GET_SEARCH_POST_SUCCESS",
  GET_SEARCH_POST_FAILURE: "GET_SEARCH_POST_FAILURE",
};
